name: CUDA Build Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up NVIDIA CUDA Toolkit
      uses: Jimver/cuda-toolkit@v0.2.14
      with:
        cuda: '12.2.0'
        no-cache: 'true'

    - name: Compile CUDA Code
      run: make